export const hellOnEarth = [
  { name: "Burning Paris", index: 3, thumb: "" },
  { name: "Outpost", index: 7, thumb: "" },
  { name: "Biotics Lab", index: 11, thumb: "" },
  { name: "Volter Manor", index: 15, thumb: "" },
  { name: "Evacuation Point", index: 23, thumb: "" },
  { name: "Catacombs", index: 27, thumb: "" },
  { name: "Black Forest", index: 97, thumb: "" },
  { name: "Farmhouse", index: 102, thumb: "" },
  { name: "Prison", index: 107, thumb: "" },
  { name: "Containment Station", index: 122, thumb: "" },
  { name: "Hostile Grounds", index: 127, thumb: "" },
  { name: "Infernal Realms", index: 153, thumb: "" },
  { name: "Zed Landing", index: 176, thumb: "" },
  { name: "The Descent", index: 181, thumb: "" },
  { name: "Nuked", index: 186, thumb: "" },
  { name: "Tragic Kingdom", index: 191, thumb: "" },
  { name: "Nightmare", index: 196, thumb: "" },
  { name: "Krampus Lair", index: 201, thumb: "" },
  { name: "Power Core", index: 211, thumb: "" },
  { name: "Airship", index: 216, thumb: "" },
  { name: "Lockdown", index: 221, thumb: "" },
  { name: "Monster Ball", index: 226, thumb: "" },
  { name: "Shopping Spree", index: 237, thumb: "" },
  { name: "Spillway", index: 242, thumb: "" },
  { name: "Steam Fortress", index: 247, thumb: "" },
  { name: "Ashwood Asylum", index: 258, thumb: "" },
  { name: "Sanitarium", index: 265, thumb: "" },
  { name: "Biolapse", index: 269, thumb: "" },
  { name: "Desolation", index: 272, thumb: "" },
  { name: "Hellmark Station", index: 275, thumb: "" },
  { name: "Elysium", index: 278, thumb: "" },
  { name: "Dystopia 2029", index: 281, thumb: "" },
  { name: "Moonbase", index: 284, thumb: "" },
  { name: "Netherhold", index: 287, thumb: "" },
  { name: "Carillon Hamlet", index: 290, thumb: "" },
  { name: "Rig", index: 293, thumb: "" },
  { name: "Barmwich Town", index: 296, thumb: "" },
  { name: "Crash", index: 299, thumb: "" },
  { name: "Subduction", index: 302, thumb: "" },
];
