export const hellOnEarth = {
  BURNING_PARIS: { name: "Burning Paris", index: 3, thumb: "" },
  OUTPOST: { name: "Outpost", index: 7, thumb: "" },
  BIOTICS_LAB: { name: "Biotics Lab", index: 11, thumb: "" },
  VOLTER_MANOR: { name: "Volter Manor", index: 15, thumb: "" },
  EVACUATION_POINT: { name: "Evacuation Point", index: 23, thumb: "" },
  CATACOMBS: { name: "Catacombs", index: 27, thumb: "" },
  BLACK_FOREST: { name: "Black Forest", index: 97, thumb: "" },
  FARMHOUSE: { name: "Farmhouse", index: 102, thumb: "" },
  PRISON: { name: "Prison", index: 107, thumb: "" },
  CONTAINMENT_STATION: { name: "Containment Station", index: 122, thumb: "" },
  HOSTILE_GROUNDS: { name: "Hostile Grounds", index: 127, thumb: "" },
  INFERNAL_REALMS: { name: "Infernal Realms", index: 153, thumb: "" },
  ZED_LANDING: { name: "Zed Landing", index: 176, thumb: "" },
  THE_DESCENT: { name: "The Descent", index: 181, thumb: "" },
  NUKED: { name: "Nuked", index: 186, thumb: "" },
  TRAGIC_KINGDOM: { name: "Tragic Kingdom", index: 191, thumb: "" },
  NIGHTMARE: { name: "Nightmare", index: 196, thumb: "" },
  KRAMPUS_LAIR: { name: "Krampus Lair", index: 201, thumb: "" },
  POWER_CORE: { name: "Power Core", index: 211, thumb: "" },
  AIRSHIP: { name: "Airship", index: 216, thumb: "" },
  LOCKDOWN: { name: "Lockdown", index: 221, thumb: "" },
  MONSTER_BALL: { name: "Monster Ball", index: 226, thumb: "" },
  SANTAS_WORKSHOP: { name: "Santa's Workshop", index: 232, thumb: "" },
  SHOPPING_SPREE: { name: "Shopping Spree", index: 237, thumb: "" },
  SPILLWAY: { name: "Spillway", index: 242, thumb: "" },
  STEAM_FORTRESS: { name: "Steam Fortress", index: 247, thumb: "" },
  ASHWOOD_ASYLUM: { name: "Ashwood Asylum", index: 258, thumb: "" },
  SANITARIUM: { name: "Sanitarium", index: 265, thumb: "" },
  BIOLAPSE: { name: "Biolapse", index: 269, thumb: "" },
  DESOLATION: { name: "Desolation", index: 272, thumb: "" },
  HELLMARK_STATION: { name: "Hellmark Station", index: 275, thumb: "" },
  ELYSIUM: { name: "Elysium", index: 278, thumb: "" },
  DYSTOPIA_2029: { name: "Dystopia 2029", index: 281, thumb: "" },
  MOONBASE: { name: "Moonbase", index: 284, thumb: "" },
  NETHERHOLD: { name: "Netherhold", index: 287, thumb: "" },
  CARILLON_HAMLET: { name: "Carillon Hamlet", index: 290, thumb: "" },
  RIG: { name: "Rig", index: 293, thumb: "" },
  BARMWICH_TOWN: { name: "Barmwich Town", index: 296, thumb: "" },
  CRASH: { name: "Crash", index: 299, thumb: "" },
  SUBDUCTION: { name: "Subduction", index: 302, thumb: "" },
};
